FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    tshark \
    tcpdump \
    python3 \
    python3-pip \
    net-tools \
    dnsutils \
    file \
    xxd \
    less \
    vim \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir \
    scapy \
    dpkt \
    python-magic

# Crear directorios de trabajo
RUN mkdir -p /pcap /output /scripts

# Script de ayuda para el estudiante
COPY scripts/hunt_smtp.sh /usr/local/bin/hunt_smtp
RUN chmod +x /usr/local/bin/hunt_smtp

WORKDIR /pcap

CMD ["bash"]
