#!/bin/bash
###############################################################################
# vol_cheatsheet.sh - Cheatsheet de Volatility 3
# Curso MAR404 - Cacería de Amenazas - Clase 5
###############################################################################

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║          VOLATILITY 3 — CHEATSHEET DE COMANDOS                 ║"
echo "╠══════════════════════════════════════════════════════════════════╣"
echo "║                                                                ║"
echo "║  INFORMACIÓN DEL SISTEMA:                                      ║"
echo "║    vol -f mem.raw windows.info                                 ║"
echo "║                                                                ║"
echo "║  PROCESOS:                                                     ║"
echo "║    vol -f mem.raw windows.pslist          (lista de procesos)  ║"
echo "║    vol -f mem.raw windows.pstree          (árbol padre-hijo)   ║"
echo "║    vol -f mem.raw windows.psscan          (scan de EPROCESS)   ║"
echo "║    vol -f mem.raw windows.cmdline         (líneas de comando)  ║"
echo "║    vol -f mem.raw windows.envars --pid N  (variables de env)   ║"
echo "║                                                                ║"
echo "║  DLLS Y MÓDULOS:                                               ║"
echo "║    vol -f mem.raw windows.dlllist --pid N (DLLs de proceso)    ║"
echo "║    vol -f mem.raw windows.modules         (módulos del kernel) ║"
echo "║    vol -f mem.raw windows.modscan         (scan de módulos)    ║"
echo "║                                                                ║"
echo "║  RED:                                                          ║"
echo "║    vol -f mem.raw windows.netscan         (conexiones activas) ║"
echo "║    vol -f mem.raw windows.netstat         (estadísticas)       ║"
echo "║                                                                ║"
echo "║  HANDLES Y REGISTROS:                                         ║"
echo "║    vol -f mem.raw windows.handles --pid N (handles abiertos)   ║"
echo "║    vol -f mem.raw windows.registry.hivelist (hives)            ║"
echo "║    vol -f mem.raw windows.registry.printkey (claves)           ║"
echo "║                                                                ║"
echo "║  MEMORIA:                                                      ║"
echo "║    vol -f mem.raw windows.memmap --pid N --dump (dump proceso) ║"
echo "║    vol -f mem.raw windows.vadinfo --pid N (VAD info)           ║"
echo "║    vol -f mem.raw windows.malfind --pid N (código inyectado)   ║"
echo "║                                                                ║"
echo "║  ARCHIVOS:                                                     ║"
echo "║    vol -f mem.raw windows.filescan        (archivos abiertos)  ║"
echo "║    vol -f mem.raw windows.dumpfiles --pid N (extraer archivos) ║"
echo "║                                                                ║"
echo "║  SERVICIOS Y DRIVERS:                                         ║"
echo "║    vol -f mem.raw windows.svcscan         (servicios)          ║"
echo "║    vol -f mem.raw windows.driverscan      (drivers cargados)   ║"
echo "║                                                                ║"
echo "║  DETECCIÓN DE MALWARE:                                        ║"
echo "║    vol -f mem.raw windows.malfind         (inyección de código)║"
echo "║    vol -f mem.raw windows.ssdt            (hooks en SSDT)      ║"
echo "║    vol -f mem.raw yarascan.YaraScan --yara-rules rule.yar     ║"
echo "║                                                                ║"
echo "╠══════════════════════════════════════════════════════════════════╣"
echo "║  FIND EVIL CHECKLIST:                                          ║"
echo "║    1. ¿Nombre correcto? (svchost vs scvhost)                   ║"
echo "║    2. ¿Path correcto? (System32 vs Temp)                       ║"
echo "║    3. ¿Parent correcto? (services.exe para svchost)            ║"
echo "║    4. ¿Instancias correctas? (1 lsass, no 2)                  ║"
echo "║    5. ¿Usuario correcto? (SYSTEM para servicios)               ║"
echo "║    6. ¿Timestamp razonable? (boot time vs post-boot)           ║"
echo "║    7. ¿Cmdline normal? (svchost -k netsvcs)                    ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
