###############################################################################
# Generator Container - Lab 10: Advanced Find Evil Dataset
# Curso MAR404 - Clase 5
###############################################################################
FROM python:3.11-slim

COPY scripts/generate_advanced_dataset.py /app/generate_advanced_dataset.py

WORKDIR /app

CMD ["python3", "generate_advanced_dataset.py"]
