#!/bin/bash
###############################################################################
# hunt_helper.sh - Guía de comandos para el Lab 2
# Curso MAR404 - Cacería de Amenazas - Clase 1
###############################################################################

echo ""
echo "================================================================"
echo "  GUÍA DE COMANDOS - Lab 2: Detección de Beaconing C2"
echo "================================================================"
echo ""
echo "=== ANÁLISIS BÁSICO ==="
echo ""
echo "  # Ver resumen del PCAP"
echo "  tshark -r /pcap/c2_beaconing.pcap -q -z io,stat,60"
echo ""
echo "  # Listar todas las conversaciones"
echo "  tshark -r /pcap/c2_beaconing.pcap -q -z conv,ip"
echo ""
echo "  # Ver solo tráfico HTTP"
echo "  tshark -r /pcap/c2_beaconing.pcap -Y 'http.request' -T fields -e frame.time -e ip.dst -e http.host -e http.user_agent"
echo ""
echo "=== DETECCIÓN DE BEACONING ==="
echo ""
echo "  # Buscar conexiones repetitivas a la misma IP"
echo "  tshark -r /pcap/c2_beaconing.pcap -Y 'http.request' -T fields -e frame.time_relative -e ip.dst | sort -t'.' -k1 -n"
echo ""
echo "  # Extraer User-Agents únicos"
echo "  tshark -r /pcap/c2_beaconing.pcap -Y 'http.user_agent' -T fields -e http.user_agent | sort -u"
echo ""
echo "  # Calcular intervalos entre conexiones a una IP específica"
echo "  tshark -r /pcap/c2_beaconing.pcap -Y 'ip.dst==203.0.113.42 && http.request' -T fields -e frame.time_relative"
echo ""
echo "=== EXTRACCIÓN DE IOCs ==="
echo ""
echo "  # Extraer todas las IPs destino únicas"
echo "  tshark -r /pcap/c2_beaconing.pcap -T fields -e ip.dst | sort -u"
echo ""
echo "  # Extraer dominios DNS consultados"
echo "  tshark -r /pcap/c2_beaconing.pcap -Y 'dns.qry.name' -T fields -e dns.qry.name | sort -u"
echo ""
echo "  # Extraer URLs completas"
echo "  tshark -r /pcap/c2_beaconing.pcap -Y 'http.request' -T fields -e http.host -e http.request.uri"
echo ""
echo "=== CON TCPDUMP ==="
echo ""
echo "  # Filtrar tráfico HTTP hacia IP sospechosa"
echo "  tcpdump -r /pcap/c2_beaconing.pcap -nn 'dst host 203.0.113.42 and tcp port 80' -A"
echo ""
echo "  # Contar paquetes por IP destino"
echo "  tcpdump -r /pcap/c2_beaconing.pcap -nn | awk '{print \$5}' | cut -d. -f1-4 | sort | uniq -c | sort -rn | head -20"
echo ""
echo "================================================================"
echo "  IOCs ESPERADOS (NO revelar a estudiantes hasta el debriefing)"
echo "================================================================"
echo "  C2 IP:         203.0.113.42"
echo "  C2 Domain:     update-service-cdn.com"
echo "  C2 User-Agent: Mozilla/5.0 (compatible; UpdateAgent/1.0)"
echo "  Beacon Path:   /api/v1/check"
echo "  Interval:      ~60 segundos (±2s jitter)"
echo "================================================================"
echo ""
