###############################################################################
# LAB 20: Web Shell Detection
# Curso MAR404 - Cacería de Amenazas (Threat Hunter) - Clase 10
###############################################################################

services:
  webshell-lab:
    build:
      context: .
      dockerfile: Dockerfile.webshell
    container_name: webshell-analyst
    stdin_open: true
    tty: true
    volumes:
      - webshell-data:/evidence
    networks:
      - hunt-net

networks:
  hunt-net:
    driver: bridge

volumes:
  webshell-data:
