FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    jq vim file && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir yara-python

COPY scripts/ /app/
WORKDIR /app

# Generate web server evidence
RUN python3 generate_webshell_evidence.py

CMD ["/bin/bash"]
